"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

format = """
$os\
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$c\
$cpp\
$rust\
$golang\
$haskell\
$python\
$nodejs\
\n \
$character\
"""

[git_branch]
symbol = " "
style = "bg:black fg:purple"
format = "[](fg:black)[ $symbol$branch ]($style)"
# ignore_branches = [ "main" ]
[git_commit]
tag_disabled = false
only_detached = false
style = "bg:prev_bg"
format = "[$hash $tag]($style)"
tag_symbol = ""
[git_status]
style = "bg:prev_bg"
format = '[[$al_status$ahead_behind](bg:black fg:blue) ]($style)[ ](fg:prev_bg)'

[os]
disabled = false
style = "bg:black fg:green"
format = "[ ](fg:black)[$symbol ]($style)"
[os.symbols]
Windows = " "
Arch = "󰣇 "

[username]
style_user = "bg:prev_bg fg:green"
style_root = "bg:prev_bg fg:red bold"
disabled = false
show_always = true
format = '[$user ]($style)[ ](fg:prev_bg)'

[directory]
style = "bg:black fg:white"
format = "[](fg:black)[ $path ]($style)[ ](fg:prev_bg)"
truncation_length = 3
truncation_symbol = "…/"

[c]
disabled = false
detect_files = ['Src/main.c', 'main.c']
symbol = " "
style = "bg:prev_bg fg:blue"
format = '[$symbol ]($style)'
[cpp]
disabled = false
detect_files = ['src/main.cpp', 'main.cpp']
detect_folders = ['src', 'Include']
symbol = " "
style = "bg:prev_bg fg:blue"
format = '[$symbol ]($style)'
[rust]
disabled = false
symbol = " "
style = "bg:prev_bg fg:yellow"
format = '[$symbol ]($style)'
[golang]
disabled = false
symbol = " "
style = "bg:prev_bg fg:green"
format = '[$symbol ]($style)'
[nodejs]
disabled = false
symbol = "󰎙 "
style = "bg:prev_bg fg:yellow"
format = '[$symbol ]($style)'
detect_files = ['index.html']
[haskell]
disabled = false
symbol = " "
style = "bg:prev_bg fg:purple"
format = '[$symbol ]($style)'
[python]
disabled = false
symbol = " "
style = "bg:prev_bg fg:yellow"
format = '[$symbol ]($style)'
