"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](blue)\
$os\
$username\
[](bg:#2c3b55 fg:blue)\
$directory\
[](bg:blue fg:#2c3b55)\
$git_branch\
$git_commit\
$git_status\
[](bg:purple fg:blue)\
$c\
$rust\
$golang\
$haskell\
$python\
[ ](fg:purple)\
"""

[git_branch]
symbol = " "
style = "bg:prev_bg"
format = "[ $symbol$branch ]($style)"
ignore_branches = [ "main" ]
[git_commit]
tag_disabled = false
only_detached = false
style = "bg:prev_bg"
format = "[ $tag ]($style)"
tag_symbol = ""
[git_status]
style = "bg:prev_bg"
format = '[[$al_status$ahead_behind](bg:blue fg:black)]($style)'

[os]
disabled = false
style = "bg:prev_fg fg:#2560aa"
[os.symbols]
Windows = " "
Arch = "󰣇 "

[username]
style_user = "bg:prev_bg fg:black dimmed bold"
style_root = "bg:prev_bg fg:red bold"
disabled = false
show_always = true
format = '[$user ]($style)'

[directory]
style = "bg:prev_bg fg:white"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[c]
disabled = false
detect_files = ['Src/main.c', 'main.c']
detect_folders = ['Src', 'Include']
symbol = " "
style = "bg:prev_bg fg:black"
format = '[ $symbol ]($style)'
# [cpp]
# disabled = false
# detect_files = ['Src/main.cpp', 'main.cpp']
# detect_folders = ['Src', 'Include']
# symbol = " "
# style = "bg:purple fg:black"
# format = '[ $symbol$name ]($style)'
[rust]
disabled = false
symbol = " "
style = "bg:prev_bg fg:black"
format = '[ $symbol ]($style)'
[golang]
disabled = false
symbol = " "
style = "bg:prev_bg fg:black"
format = '[ $symbol ]($style)'
[nodejs]
disabled = false
symbol = "󰎙 "
style = "bg:prev_bg fg:black"
format = '[ $symbol ]($style)'
[haskell]
disabled = false
symbol = " "
style = "bg:prev_bg fg:black"
format = '[ $symbol ]($style)'
[python]
disabled = false
symbol = " "
style = "bg:prev_bg fg:black"
format = '[ $symbol ]($style)'
